[package]
name = "tarball"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = "1.0"
tar = "0.4"
contract = { path = "../contract" }
tokio = { version = "1.48.0", features = ["rt", "macros"] }

[dev-dependencies]
tempfile = "3.10"
