[package]
name = "actor"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
contract = { path = "../contract" }
pipeline = { path = "../pipeline" }
package = { path = "../package" }
debug = { path = "../debug" }
tokio = { version = "1.48.0", features = ["full"] }
