[package]
name = "resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
package = { path = "../package" }
contract = { path = "../contract" }
anyhow = "1.0"

[lints]
workspace = true
