[workspace]
members = [
    "apps/craft",
    "crates/manager",
    "crates/package",
    "crates/actor",
    "crates/progress",
    "crates/cli",
    "crates/resolver",
]
resolver = "2"

[workspace.lints.clippy]
unwrap_used = "deny"
