[package]
name = "debug"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
contract = { path = "../contract" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
